# Generated by Django 3.2.9 on 2021-12-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Optical Service', 'Optical Service'), ('Dental Service', 'Dental Service'), ('Pediatric Service', 'Pediatric Service'), ('Laboratory Service', 'Laboratory Service')], max_length=250),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('8AM TO 10AM', '8AM TO 10AM'), ('10AM TO 12PM', '10AM TO 12PM'), ('12PM TO 2PM', '12PM TO 2PM'), ('2PM TO 4PM', '2PM TO 4PM'), ('4PM TO 6PM', '4PM TO 6PM'), ('6PM TO 8PM', '6PM TO 8PM'), ('4PM TO 10PM', '4PM TO 10PM'), ('10PM TO 12PM', '10PM TO 12PM')], max_length=250),
        ),
        migrations.AlterField(
            model_name='patientsrecords',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Binary', 'Binary')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patientsrecords',
            name='recent_diagnosis',
            field=models.CharField(choices=[('Malaria', 'Malaria'), ('Fever', 'Fever'), ('Cholera', 'Cholera'), ('Cancer', 'Cancer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patientsrecords',
            name='self_medication',
            field=models.CharField(choices=[('No', 'No'), ('Always', 'Always')], max_length=255),
        ),
        migrations.AlterField(
            model_name='patientsrecords',
            name='smoke_drink',
            field=models.CharField(choices=[('Smokes', 'Smokes'), ('Drinks', 'Drinks'), ('Smokes and Drinks', 'Smokes and Drinks'), ('None', 'None')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patientsrecords',
            name='sport_participation',
            field=models.CharField(choices=[('No', 'No'), ('Sometimes', 'Sometimes'), ('Always', 'Always')], max_length=50),
        ),
    ]
