# Generated by Django 3.2.9 on 2021-12-08 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20211207_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsrecords',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
